// Generated from ref/9router@39e36d3 by tools/gen-bundled/generate.mjs — do not edit.

/// `oauth.params` keys the core knows. Anything else is rejected (research R5).
pub const KNOWN_OAUTH_PARAMS: &[&str] = &[
    "api_version",
    "auth_methods",
    "authorize_url_path",
    "callback_param",
    "callback_path",
    "chat_endpoint",
    "client_name",
    "client_type",
    "client_version",
    "custom",
    "db_keys",
    "editor_plugin_version",
    "editor_version",
    "extra_params",
    "fixed_port",
    "grant_types",
    "kn",
    "load_code_assist_user_agent",
    "max_refresh_age_ms",
    "models_endpoint",
    "platform",
    "poll_interval",
    "referrer",
    "refresh",
    "rsa_key_exchange",
    "token_url_path",
    "track_refresh_at",
    "user_agent",
    "user_info_url_path",
];
