//! Text handling for Cargo.lock (format version 4): blocks are `[[package]]` tables separated
//! by one blank line, sorted by name. Cargo's `--locked` compares the file as text, so the
//! output keeps that exact shape.

const SOURCE: &str = "registry+https://github.com/rust-lang/crates.io-index";

struct Lock {
    header: String,
    blocks: Vec<String>,
}

fn parse(text: &str) -> Lock {
    let mut header = String::new();
    let mut blocks: Vec<String> = Vec::new();
    for line in text.lines() {
        if line == "[[package]]" {
            blocks.push(String::from("[[package]]"));
        } else if let Some(last) = blocks.last_mut() {
            last.push('\n');
            last.push_str(line);
        } else {
            header.push_str(line);
            header.push('\n');
        }
    }
    for b in &mut blocks {
        b.truncate(b.trim_end().len());
    }
    Lock { header: header.trim_end().to_owned(), blocks }
}

fn render(lock: &Lock) -> String {
    format!("{}\n\n{}\n", lock.header, lock.blocks.join("\n\n"))
}

fn field<'a>(block: &'a str, key: &str) -> Option<&'a str> {
    let prefix = format!("{key} = \"");
    block.lines().find_map(|l| l.strip_prefix(&prefix)?.strip_suffix('"'))
}

/// The seed lock, resolved with the kit as a path dependency of `seed_name`, turned into the
/// pinned lock for builds: the seed package goes, and the kit becomes a registry package whose
/// checksum is the one in its `.cargo-checksum.json`.
pub(crate) fn pin(seed_lock: &str, seed_name: &str, kit_name: &str, kit_checksum: &str) -> String {
    let mut lock = parse(seed_lock);
    lock.blocks.retain(|b| field(b, "name") != Some(seed_name));
    for b in &mut lock.blocks {
        if field(b, "name") == Some(kit_name) {
            let mut lines: Vec<String> = b.lines().map(str::to_owned).collect();
            if let Some(at) = lines.iter().position(|l| l.starts_with("version = ")) {
                lines.insert(at + 1, format!("source = \"{SOURCE}\""));
                lines.insert(at + 2, format!("checksum = \"{kit_checksum}\""));
            }
            *b = lines.join("\n");
        }
    }
    render(&lock)
}

/// The pinned lock plus the package's own entry. An adapter depends on the kit and nothing
/// else (the gate guarantees it), so its entry has that single dependency.
pub(crate) fn with_root(pinned: &str, name: &str, version: &str, kit_name: &str) -> String {
    let mut lock = parse(pinned);
    let root = format!("[[package]]\nname = \"{name}\"\nversion = \"{version}\"\ndependencies = [\n \"{kit_name}\",\n]");
    let at = lock.blocks.iter().position(|b| field(b, "name").is_some_and(|n| n > name)).unwrap_or(lock.blocks.len());
    lock.blocks.insert(at, root);
    render(&lock)
}

#[cfg(test)]
mod tests {
    use super::*;

    const SEED: &str = "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"itoa\"\nversion = \"1.0.18\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"abc\"\n\n[[package]]\nname = \"nr-builder-seed\"\nversion = \"0.0.0\"\ndependencies = [\n \"nullrouter-adapter-kit\",\n]\n\n[[package]]\nname = \"nullrouter-adapter-kit\"\nversion = \"1.0.0\"\ndependencies = [\n \"itoa\",\n]\n";

    #[test]
    fn pinning_drops_the_seed_and_checksums_the_kit() {
        let pinned = pin(SEED, "nr-builder-seed", "nullrouter-adapter-kit", "dead");
        assert!(!pinned.contains("nr-builder-seed"));
        assert!(pinned.contains("name = \"nullrouter-adapter-kit\"\nversion = \"1.0.0\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"dead\"\ndependencies"));
        assert!(pinned.starts_with("# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]"));
        assert!(pinned.ends_with("]\n"));
    }

    #[test]
    fn the_root_lands_in_name_order() {
        let pinned = pin(SEED, "nr-builder-seed", "nullrouter-adapter-kit", "dead");
        let out = with_root(&pinned, "nr-adapter-x", "0.3.0", "nullrouter-adapter-kit");
        let names: Vec<_> = parse(&out).blocks.iter().filter_map(|b| field(b, "name").map(str::to_owned)).collect();
        assert_eq!(names, ["itoa", "nr-adapter-x", "nullrouter-adapter-kit"]);
        assert!(out.contains("name = \"nr-adapter-x\"\nversion = \"0.3.0\"\ndependencies = [\n \"nullrouter-adapter-kit\",\n]\n\n[[package]]"));
    }
}
