//! Sign-in parity with 9router (spec 005 T040, Constitution VI): the fixtures in
//! `tests/fixtures/9router/oauth/`, generated by `tools/gen-bundled/oauth-oracle.mjs` from
//! 9router's own sign-in and refresh modules.
//!
//! Live: the bundled plugins' `[signin]` data, authorize URLs, code-exchange and device-grant
//! bodies (driven through the real flows against the mock identity provider), refresh request
//! shape, and token-endpoint error codes with their transient/permanent split. Deliberate
//! deviations (research R19, and the ones this file names) are asserted as deviations.
//!
//! Ignored until built: the refresh call (T050), its classification (T051) and the
//! maintenance selection (T054). Each ignored test names the API it expects.

use std::collections::{BTreeMap, BTreeSet};
use std::time::Duration;

use nullrouter_engine::signin::{self, Begun, SignInError, SignInHttp, encode_body, pkce};
use nullrouter_engine::testkit::mock_idp::{AUTHORIZE, DEVICE, DISCOVERY, PROFILE, TOKEN};
use nullrouter_engine::testkit::{MockIdp, MockUpstream, Step};
use nullrouter_registry::schema::{RedirectKind, SignInDecl, SignInFlow, TokenBody};
use nullrouter_registry::validate::validate_with;
use nullrouter_registry::{PluginSource, ProviderEntity};
use serde_json::{Value, json};
use tokio_util::sync::CancellationToken;

fn fixture(name: &str) -> Value {
    let path = format!("{}/../../tests/fixtures/9router/oauth/{name}", env!("CARGO_MANIFEST_DIR"));
    let text =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{path}: {e}; run tools/gen-bundled/generate.mjs"));
    let v: Value = serde_json::from_str(&text).unwrap();
    assert!(v["source"].as_str().unwrap().starts_with("Generated from ref/9router@"));
    v["data"].clone()
}

fn bundled_src(id: &str) -> String {
    std::fs::read_to_string(format!("{}/../../plugins/bundled/{id}.toml", env!("CARGO_MANIFEST_DIR"))).unwrap()
}

fn entity(id: &str, src: &str, allow_private: bool) -> ProviderEntity {
    let ctx = nullrouter_registry::bundled_gate_ctx(false, allow_private).unwrap();
    validate_with(src, PluginSource::Bundled, &format!("{id}.toml"), &ctx)
        .unwrap_or_else(|e| panic!("{id}: {e:#?}"))
        .entity
}

fn decl(id: &str) -> SignInDecl {
    entity(id, &bundled_src(id), false).signin.unwrap_or_else(|| panic!("{id} has [signin]"))
}

/// The bundled plugin with its sign-in URLs moved to the mock identity provider. Redirects
/// stay as declared.
fn at_mock(idp: &MockIdp, id: &str) -> ProviderEntity {
    let d = decl(id);
    let mut src = bundled_src(id);
    let mut swap = |from: Option<&str>, to: &str| {
        if let Some(from) = from {
            src = src.replace(&format!("\"{from}\""), &format!("\"{}\"", idp.url(to)));
        }
    };
    swap(d.discovery_url.as_deref(), DISCOVERY);
    swap(d.authorize_url.as_deref(), AUTHORIZE);
    swap(Some(&d.token_url), TOKEN);
    swap(d.device_url.as_deref(), DEVICE);
    swap(d.profile.as_ref().map(|p| p.url.as_str()), PROFILE);
    idp.set_client_id(&d.client_id);
    entity(id, &src, true)
}

fn strs(v: &Value) -> Vec<String> {
    v.as_array().unwrap().iter().map(|s| s.as_str().unwrap().to_owned()).collect()
}

/// A recorded body's field names and values.
fn fields(body: &Value) -> BTreeMap<String, String> {
    body["fields"]
        .as_array()
        .unwrap()
        .iter()
        .map(|kv| (kv[0].as_str().unwrap().to_owned(), kv[1].as_str().unwrap().to_owned()))
        .collect()
}

fn encoding(kind: TokenBody) -> &'static str {
    match kind {
        TokenBody::Form => "form",
        TokenBody::Json => "json",
    }
}

fn http() -> SignInHttp {
    SignInHttp::new(true).with_timeout(Duration::from_secs(5))
}

#[test]
fn bundled_signin_declarations_match_9router() {
    let data = fixture("providers.json");
    for (id, want) in data["providers"].as_object().unwrap() {
        let d = decl(id);
        assert_eq!(d.client_id, want["client_id"].as_str().unwrap(), "{id} client_id");
        assert_eq!(d.scopes, strs(&want["scopes"]), "{id} scopes");
        assert_eq!(d.token_url, want["token_url"].as_str().unwrap(), "{id} token_url");
        assert_eq!(encoding(d.body), want["token_body"].as_str().unwrap(), "{id} token body");
        assert_eq!(d.refresh_lead.as_millis(), u128::from(want["refresh_lead_ms"].as_u64().unwrap()), "{id} lead");
        match want["flow"].as_str().unwrap() {
            "device_code" => {
                assert_eq!(d.flow, SignInFlow::DeviceCode, "{id}");
                assert_eq!(d.device_url.as_deref(), want["device_url"].as_str(), "{id} device_url");
                if let Some(r) = want.get("refresh_url") {
                    assert_eq!(Some(d.token_url.as_str()), r.as_str(), "{id}: refresh goes to the token URL");
                }
                for (k, v) in want["params"].as_object().unwrap() {
                    let ours = d.params.iter().find(|(p, _)| format!("{p:?}").eq_ignore_ascii_case(k));
                    let ours = ours.map(|(_, v)| pkce::param_value(v));
                    assert_eq!(ours.as_deref(), v.as_str(), "{id} param {k}");
                }
            }
            _ => {
                assert_eq!(d.flow, SignInFlow::Pkce, "{id}");
                assert_eq!(d.authorize_url.as_deref(), want["authorize_url"].as_str(), "{id} authorize_url");
                assert_eq!(d.discovery_url.as_deref(), want["discovery_url"].as_str(), "{id} discovery_url");
                assert_eq!(u64::from(d.verifier_len()), want["verifier_bytes"].as_u64().unwrap(), "{id} verifier");
            }
        }
    }

    // xai: the same loopback redirect.
    let xai = decl("xai");
    assert_eq!(xai.redirect[0].uri, data["providers"]["xai"]["redirect_uri"].as_str().unwrap());
    assert_eq!(xai.redirect[0].kind, RedirectKind::Loopback);
    // Deviation (R19, R4): 9router's claude sign-in has only the dashboard's localhost
    // redirect; 0router offers Anthropic's hosted code page first, loopback second.
    let anthropic = decl("anthropic");
    assert!(data["providers"]["anthropic"]["redirect_uri"].is_null());
    assert_eq!(
        anthropic.redirect.iter().map(|r| r.kind).collect::<Vec<_>>(),
        [RedirectKind::CodePage, RedirectKind::Loopback]
    );
}

/// Query pairs, decoded, with a 32-hex nonce as 9router's oracle records it.
fn decoded_pairs(url: &str) -> (String, Vec<(String, String)>) {
    let u = url::Url::parse(url).unwrap();
    let base = format!("{}://{}{}", u.scheme(), u.host_str().unwrap(), u.path());
    let mut pairs: Vec<(String, String)> = u
        .query_pairs()
        .map(|(k, v)| {
            let hex = v.len() == 32 && v.chars().all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase());
            (k.clone().into_owned(), if k == "nonce" && hex { "{random.hex16}".into() } else { v.into_owned() })
        })
        .collect();
    pairs.sort();
    (base, pairs)
}

#[test]
fn authorize_urls_match_9router() {
    let data = fixture("authorize.json");
    let mut seen = 0;
    for c in data["cases"].as_array().unwrap() {
        let name = c["name"].as_str().unwrap();
        let id = c["provider"].as_str().unwrap();
        let d = decl(id);
        if let Some(len) = c.get("verifier_len") {
            // generateAuthData: verifier and state lengths.
            assert_eq!(pkce::verifier(d.verifier_len()).len() as u64, len.as_u64().unwrap(), "{name}");
            assert_eq!(pkce::state().len() as u64, c["state_len"].as_u64().unwrap(), "{name}");
            continue;
        }
        let input = &c["input"];
        let ours = pkce::authorize_url(
            c["base"].as_str().unwrap(),
            &d,
            input["redirect_uri"].as_str().unwrap(),
            input["challenge"].as_str().unwrap(),
            input["state"].as_str().unwrap(),
        );
        let (base, pairs) = decoded_pairs(&ours);
        assert_eq!(base, c["base"].as_str().unwrap(), "{name}");
        let mut want: Vec<(String, String)> = c["params"]
            .as_array()
            .unwrap()
            .iter()
            .map(|kv| (kv[0].as_str().unwrap().to_owned(), kv[1].as_str().unwrap().to_owned()))
            .collect();
        want.sort();
        assert_eq!(pairs, want, "{name}: same parameters and values (order is not significant)");

        let query = c["query"].as_str().unwrap();
        if query.contains("scope=org%3Acreate_api_key+user") {
            // Deviation: 9router's claude URL comes from URLSearchParams (space as `+`); 0router
            // encodes every authorize URL like encodeURIComponent (`%20`), as 9router's xai does.
            // Both decode to the same scope.
            assert!(ours.contains("scope=org%3Acreate_api_key%20user%3Aprofile%20user%3Ainference"), "{ours}");
        } else {
            assert!(ours.contains(query.split('&').find(|p| p.starts_with("scope=")).unwrap()), "{name}: {ours}");
        }
        seen += 1;
    }
    assert_eq!(seen, 3);
}

#[tokio::test]
async fn xai_code_exchange_sends_9routers_form_body() {
    let want = fixture("token-requests.json")["cases"]
        .as_array()
        .unwrap()
        .iter()
        .find(|c| c["name"] == "xai-code-exchange")
        .unwrap()
        .clone();
    let idp = MockIdp::start().await;
    idp.set_id_claims(Some(json!({ "email": want["result"]["email"], "sub": "s-2" })));
    let p = at_mock(&idp, "xai");
    let Begun::Pkce(mut s) = signin::begin(&http(), &p).await.unwrap() else { panic!("xai is pkce") };
    let location = idp.browse(s.authorize_url()).await;
    let code = s.wait_code(async move { Some(location) }, &CancellationToken::new()).await.unwrap();
    let e = s.complete(&http(), "main", code).await.unwrap();

    let sent = idp.token_requests().pop().unwrap();
    // calls[0] is discovery (as 0router does it), then the exchange at the discovered URL.
    assert!(want["calls"][0]["url"].as_str().unwrap().ends_with("/.well-known/openid-configuration"));
    let call = &want["calls"][1];
    assert_eq!(call["body"]["encoding"], if sent.json { "json" } else { "form" });
    let theirs = fields(&call["body"]);
    assert_eq!(sent.fields.keys().collect::<BTreeSet<_>>(), theirs.keys().collect::<BTreeSet<_>>());
    for k in ["grant_type", "client_id"] {
        assert_eq!(sent.get(k), theirs.get(k).map(String::as_str), "{k}");
    }
    assert_eq!(sent.get("redirect_uri"), Some(s.redirect_uri()));
    assert_eq!(sent.get("code_verifier").unwrap().len(), 128, "96-byte verifier, as 9router");
    // 9router's mapTokens reads the email from the id token; so does 0router (no profile).
    assert_eq!(e.claims.email.as_deref(), want["result"]["email"].as_str());
}

#[tokio::test]
async fn anthropic_code_exchange_sends_9routers_json_body() {
    let cases = fixture("token-requests.json");
    let want = cases["cases"].as_array().unwrap().iter().find(|c| c["name"] == "anthropic-code-exchange").unwrap();
    let idp = MockIdp::start().await;
    let p = at_mock(&idp, "anthropic");
    let Begun::Pkce(mut s) = signin::begin(&http(), &p).await.unwrap() else { panic!("anthropic is pkce") };
    // The hosted code page is the first redirect (R19); the operator pastes its address.
    assert_eq!(s.redirect_kind(), RedirectKind::CodePage);
    let location = idp.browse(s.authorize_url()).await;
    let code = s.wait_code(async move { Some(location) }, &CancellationToken::new()).await.unwrap();
    s.complete(&http(), "main", code).await.unwrap();

    let sent = idp.token_requests().pop().unwrap();
    let call = &want["calls"][0];
    assert_eq!(call["headers"]["content-type"], "application/json");
    assert!(sent.json, "JSON body, as 9router");
    let theirs = fields(&call["body"]);
    assert_eq!(sent.fields.keys().collect::<BTreeSet<_>>(), theirs.keys().collect::<BTreeSet<_>>());
    assert_eq!(sent.get("grant_type"), Some("authorization_code"));
    assert_eq!(sent.get("client_id"), theirs.get("client_id").map(String::as_str));
    assert!(sent.get("state").is_some_and(|st| !st.is_empty()), "state travels in the JSON body");
    // 9router splits a pasted `code#state` and sends the page's state.
    let split = cases["cases"].as_array().unwrap().iter().find(|c| c["name"] == "anthropic-code-hash-state").unwrap();
    let f = fields(&split["calls"][0]["body"]);
    assert_eq!((f["code"].as_str(), f["state"].as_str()), ("auth-code", "state-from-page"));
    let pasted = s.parse_paste("auth-code#nope");
    assert!(pasted.is_err(), "0router checks a pasted state instead of sending it on");
}

#[tokio::test]
async fn grok_cli_device_grant_sends_9routers_bodies() {
    let cases = fixture("token-requests.json");
    let by = |n: &str| cases["cases"].as_array().unwrap().iter().find(|c| c["name"] == n).unwrap().clone();
    let idp = MockIdp::start().await;
    let p = at_mock(&idp, "grok-cli");
    let Begun::Device(mut d) = signin::begin(&http(), &p).await.unwrap() else { panic!("grok-cli is device code") };
    d.poll(&http(), "main", &CancellationToken::new()).await.unwrap();

    let device = idp.device_requests().pop().unwrap();
    let want = fields(&by("grok-cli-device-request")["calls"][0]["body"]);
    assert!(!device.json);
    assert_eq!(device.fields, want, "client_id, scope (all eight) and referrer=grok-build");

    let poll = idp.token_requests().pop().unwrap();
    let want = fields(&by("grok-cli-device-granted")["calls"][0]["body"]);
    assert!(!poll.json);
    assert_eq!(poll.fields.keys().collect::<BTreeSet<_>>(), want.keys().collect::<BTreeSet<_>>());
    assert_eq!(poll.get("grant_type"), want.get("grant_type").map(String::as_str));
    assert_eq!(poll.get("client_id"), want.get("client_id").map(String::as_str));

    // 9router's poll outcomes: pending and slow_down keep waiting, the rest end the sign-in.
    for (n, pending) in [("grok-cli-device-pending", true), ("grok-cli-device-slow-down", false)] {
        let r = &by(n)["result"];
        assert_eq!((r["success"].as_bool(), r["pending"].as_bool()), (Some(false), Some(pending)), "{n}");
    }
    for n in ["grok-cli-device-expired", "grok-cli-device-denied"] {
        assert!(by(n)["result"].get("pending").is_none(), "{n} ends the sign-in");
    }
}

/// The refresh request 9router sends: the provider's token URL and encoding, and exactly
/// `grant_type=refresh_token`, `refresh_token`, `client_id` (T050 builds the same).
#[test]
fn refresh_requests_use_the_declared_token_url_encoding_and_fields() {
    let data = fixture("refresh.json");
    let cases = data["cases"].as_array().unwrap();
    assert_eq!(cases.len(), 6);
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let d = decl(c["provider"].as_str().unwrap());
        let call = &c["calls"][0];
        assert_eq!(call["url"].as_str(), Some(d.token_url.as_str()), "{name}");
        let (ct, _) = encode_body(d.body, &[]);
        assert_eq!(call["headers"]["content-type"].as_str(), Some(ct), "{name}");
        let f = fields(&call["body"]);
        assert_eq!(
            f.keys().map(String::as_str).collect::<BTreeSet<_>>(),
            BTreeSet::from(["client_id", "grant_type", "refresh_token"])
        );
        assert_eq!(
            (f["grant_type"].as_str(), f["client_id"].as_str()),
            ("refresh_token", d.client_id.as_str()),
            "{name}"
        );
        assert_eq!(f["refresh_token"], c["input"]["refresh_token"].as_str().unwrap(), "{name}");
        // Rotation (research R9, providers.js:131): the old refresh token stays when the
        // response has none.
        let kept = c["result"]["refreshToken"].as_str().unwrap();
        let want =
            c["response"]["refresh_token"].as_str().unwrap_or_else(|| c["input"]["refresh_token"].as_str().unwrap());
        assert_eq!(kept, want, "{name}");
    }
    // Without a refresh token nothing is sent.
    assert!(data["guards"].as_array().unwrap().iter().all(|g| g["result"].is_null() && g["calls"] == 0));
}

/// Research R10's class of a token-endpoint failure: `None` where R10 says nothing (404).
fn r10_permanent(status: Option<u64>) -> Option<bool> {
    match status {
        None => Some(false),
        Some(400 | 401 | 403) => Some(true),
        Some(429 | 500..=599) => Some(false),
        Some(_) => None,
    }
}

/// Every refresh-error case answered by a mock token endpoint and read by 0router's token
/// request: the error code 9router's classifier reads, and the transient/permanent split.
#[tokio::test]
async fn refresh_errors_read_9routers_codes_and_split_like_r10() {
    let data = fixture("refresh-errors.json");
    let cases = data["cases"].as_array().unwrap();
    assert_eq!(cases.len(), 15);
    let mock = MockUpstream::start().await;
    let body =
        encode_body(TokenBody::Form, &[("grant_type", "refresh_token"), ("refresh_token", "r"), ("client_id", "c")]);
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let status = c["status"].as_u64();
        let url = match status {
            Some(s) => {
                let s = u16::try_from(s).unwrap();
                mock.push([match &c["body"] {
                    Value::String(t) => Step::Reply { status: s, headers: vec![], body: t.clone().into() },
                    v => Step::json(s, v.clone()),
                }]);
                mock.url("/oauth2/token")
            }
            // A closed port: connection failure.
            None => format!("http://127.0.0.1:{}/oauth2/token", closed_port()),
        };
        let err = signin::token_request(&http(), &url, body.clone()).await.unwrap_err();

        if let Some(permanent) = r10_permanent(status) {
            assert_eq!(err.is_transient(), !permanent, "{name}: {err}");
        }
        match (&err, &c["classify"]["code"]) {
            (SignInError::Rejected { code, .. }, Value::String(theirs)) if !theirs.is_empty() => {
                if name == "error-code-field" {
                    // Deviation: 9router's classifier also reads `error_code`; 0router reads
                    // `error` only and reports the status. The class is the same (400).
                    assert_eq!(code, "HTTP 400", "{name}");
                } else {
                    assert_eq!(code, theirs, "{name}");
                }
            }
            (SignInError::Rejected { code, status: s, .. }, _) => assert_eq!(code, &format!("HTTP {s}"), "{name}"),
            (SignInError::Transport { .. }, _) => assert!(status.is_none(), "{name}"),
            (other, _) => panic!("{name}: {other}"),
        }

        // Deviation (R19, FR-015): 9router's claude refresh returns null for every failure and
        // its xai/grok-cli refresh flags only invalid_grant/invalid_request, so a dead refresh
        // token is retried forever. 0router reads every 400/401/403 as permanent.
        assert_eq!(c["refresh"]["anthropic"]["unrecoverable"], false, "{name}");
        let flagged = c["refresh"]["xai"]["unrecoverable"].as_bool().unwrap();
        assert_eq!(flagged, matches!(name, "invalid-grant" | "invalid-request" | "error-code-field"), "{name}");
        assert_eq!(c["refresh"]["grok-cli"], c["refresh"]["xai"], "{name}: grok-cli refreshes like xai");
        if status.is_some_and(|s| matches!(s, 400 | 401 | 403)) {
            assert!(!err.is_transient(), "{name}: permanent in 0router whatever 9router does");
        }
    }
}

fn closed_port() -> u16 {
    let l = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
    l.local_addr().unwrap().port()
}

#[test]
fn refresh_leads_match_and_background_lead_is_a_deviation() {
    let data = fixture("refresh-schedule.json");
    let providers = fixture("providers.json");
    let background = Duration::from_millis(providers["background_refresh_lead_ms"].as_u64().unwrap());
    for c in data["cases"].as_array().unwrap() {
        let id = c["provider"].as_str().unwrap();
        let lead = decl(id).refresh_lead;
        let Some(minutes) = c["expires_in_minutes"].as_i64() else { continue };
        if c["auth_type"] != "oauth" || c["has_refresh_token"] == false {
            assert_eq!(c["selected"], false);
            continue;
        }
        // 9router's background task refreshes at max(lead, 30 min) before expiry; 0router
        // refreshes at the plugin's lead (research R9). The two agree whenever the lead is the
        // larger (anthropic's 4 h) and differ for xai and grok-cli between 5 and 30 minutes.
        let remaining = Duration::from_secs(u64::try_from(minutes.max(0)).unwrap() * 60);
        let theirs = minutes < 0 || remaining < lead.max(background);
        assert_eq!(c["selected"].as_bool(), Some(theirs), "{id} {}", c["name"]);
        let ours = minutes < 0 || remaining < lead;
        if lead >= background {
            assert_eq!(ours, theirs, "{id} {}", c["name"]);
        }
    }
}

// ── Ignored until the refresh and maintenance tasks land ─────────────────────

/// T050: `signin::refresh::refresh(http, &ProviderEntity, &TokenEntry) -> Result<TokenEntry,
/// SignInError>` against the mock identity provider for each `refresh.json` case: the request
/// fields equal 9router's, and the stored refresh token rotates or stays as `result`.
#[test]
#[ignore = "T050/T051: refresh not built yet"]
fn refresh_call_rotates_like_9router() {
    let cases = fixture("refresh.json")["cases"].as_array().unwrap().len();
    assert_eq!(cases, 6);
    todo!("T050: run each case through signin::refresh::refresh against MockIdp (set_rotation per case)");
}

/// T051: `signin::classify::classify(&SignInError) -> RefreshClass { Permanent, Transient }`
/// for every `refresh-errors.json` case: Permanent for R10's codes and any other
/// 400/401/403, Transient for 429, 5xx and transport failures.
#[test]
#[ignore = "T050/T051: refresh not built yet"]
fn refresh_failures_classify_per_r10() {
    let cases = fixture("refresh-errors.json")["cases"].as_array().unwrap().len();
    assert_eq!(cases, 15);
    todo!("T051: classify each case's SignInError and compare with r10_permanent()");
}

/// T054: the maintenance queue picks each sign-in account at `expires_at - refresh_lead`;
/// replay `refresh-schedule.json` (sign-in accounts only; key accounts never refresh).
#[test]
#[ignore = "T054: maintenance task not built yet"]
fn maintenance_selects_accounts_due_for_refresh() {
    let cases = fixture("refresh-schedule.json")["cases"].as_array().unwrap().len();
    assert_eq!(cases, 33);
    todo!("T054: feed each case to the maintenance queue's due check");
}
