//! Quota parity with 9router (spec 005 T040, Constitution VI): the fixtures in
//! `tests/fixtures/9router/usage/` (`quota-*.json`, `grpc-web.json`, `reset-time.json`,
//! `dispatch.json`, `models-grok-cli.json`), generated by `tools/gen-bundled/oauth-oracle.mjs`
//! from 9router's usage readers. `usage/cases.json` (token counts) belongs to slice 003.
//!
//! Live now: the fixtures load with the expected cases, the windows 9router reports keep the
//! invariants the extractor will be held to, the testkit's gRPC-web sample is byte-identical
//! to 9router's encoder, and 0router's window names map one-to-one onto 9router's.
//!
//! Ignored until built: the extractor (T070), the gRPC-web decoder (T071), the bundled
//! `[quota]` sections (T074) and the live model list (T076). Each names the API it expects.

use std::collections::BTreeMap;

use nullrouter_engine::testkit::mock_quota::samples;
use serde_json::Value;

fn fixture(name: &str) -> Value {
    let path = format!("{}/../../tests/fixtures/9router/usage/{name}", env!("CARGO_MANIFEST_DIR"));
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{path}: {e}; run tools/gen-bundled/generate.mjs"));
    let v: Value = serde_json::from_str(&text).unwrap();
    assert!(v["source"].as_str().unwrap().starts_with("Generated from ref/9router@"));
    v["data"].clone()
}

fn hex(s: &str) -> Vec<u8> {
    (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap()).collect()
}

/// 0router's window name (research R11) for 9router's quota key, per provider.
fn our_name(provider: &str, theirs: &str) -> String {
    match provider {
        "anthropic" => match theirs {
            "session (5h)" => "5-hour".into(),
            "weekly (7d)" => "weekly".into(),
            t => t.strip_suffix(" (7d)").unwrap_or(t).to_owned(),
        },
        "opencode-go" | "opencode-zen" => theirs.to_lowercase(),
        _ => match theirs {
            "Weekly SuperGrok" => "weekly SuperGrok".into(),
            t => t.to_lowercase(),
        },
    }
}

/// Every quota window 9router reports, by case: `(case, provider, name, window)`.
fn windows() -> Vec<(String, String, String, Value)> {
    let mut out = Vec::new();
    let mut push = |case: &str, provider: &str, result: &Value| {
        if let Some(q) = result["quotas"].as_object() {
            for (k, w) in q {
                out.push((case.to_owned(), provider.to_owned(), k.clone(), w.clone()));
            }
        }
    };
    for c in fixture("quota-claude.json")["cases"].as_array().unwrap() {
        push(c["name"].as_str().unwrap(), "anthropic", &c["result"]);
    }
    let grok = fixture("quota-grok-cli.json");
    for c in grok["parse"].as_array().unwrap().iter().chain(grok["flow"].as_array().unwrap()) {
        push(c["name"].as_str().unwrap(), "grok-cli", &c["result"]);
    }
    for c in fixture("quota-opencode.json")["cases"].as_array().unwrap() {
        push(c["name"].as_str().unwrap(), c["provider"].as_str().unwrap(), &c["result"]);
    }
    out
}

#[test]
fn fixtures_load_with_every_case() {
    assert_eq!(fixture("quota-claude.json")["cases"].as_array().unwrap().len(), 4);
    let grok = fixture("quota-grok-cli.json");
    assert_eq!((grok["parse"].as_array().unwrap().len(), grok["flow"].as_array().unwrap().len()), (10, 9));
    assert_eq!(fixture("quota-opencode.json")["cases"].as_array().unwrap().len(), 20);
    let g = fixture("grpc-web.json");
    assert_eq!((g["frames"].as_array().unwrap().len(), g["headers"].as_array().unwrap().len()), (16, 7));
    assert_eq!(fixture("reset-time.json")["cases"].as_array().unwrap().len(), 12);
    assert_eq!(fixture("dispatch.json")["cases"].as_array().unwrap().len(), 8);
    assert_eq!(fixture("models-grok-cli.json")["parse"].as_array().unwrap().len(), 3);
    assert_eq!(windows().len(), 40);
}

/// What the extractor will be held to: a percent window has total 100 and remaining
/// `100 - used` floored at 0; a counted window has remaining `total - used` (as a percentage
/// of total); a reset is an RFC 3339 instant or absent.
#[test]
fn reported_windows_keep_the_extractors_invariants() {
    for (case, provider, name, w) in windows() {
        let used = w["used"].as_f64().unwrap();
        let total = w["total"].as_f64().unwrap();
        let pct = w["remainingPercentage"].as_f64().unwrap();
        assert_eq!(w["unlimited"], false, "{case} {name}");
        assert!(total > 0.0, "{case} {name}");
        // 9router's one inconsistent row: a credits bag with only `balance: 0` becomes a
        // synthetic "0 used of 1, 0% left" bar (grok-cli.js:272-279). The extractor reports
        // what the provider said instead: remaining 0.
        if (case.as_str(), used, total) != ("credits-bag-balance-only", 0.0, 1.0) {
            let want = ((total - used).max(0.0) / total) * 100.0;
            assert!((pct - want).abs() < 1e-9, "{case} {provider} {name}: {pct} vs {want}");
        }
        if let Some(r) = w["remaining"].as_f64() {
            assert_eq!(total, 100.0, "{case} {name}: only percent windows carry `remaining`");
            assert!((r - (100.0 - used).max(0.0)).abs() < 1e-9, "{case} {name}");
        }
        match &w["resetAt"] {
            Value::Null => {}
            Value::String(s) => assert!(s.ends_with('Z') && s.len() == 24, "{case} {name}: {s}"),
            v => panic!("{case} {name}: {v}"),
        }
    }
}

#[test]
fn window_names_map_one_to_one() {
    let mut by_provider: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();
    for (_, provider, theirs, _) in windows() {
        let ours = our_name(&provider, &theirs);
        let seen = by_provider.entry(provider.clone()).or_default();
        if let Some(prev) = seen.insert(ours.clone(), theirs.clone()) {
            assert_eq!(prev, theirs, "{provider}: {ours} would merge two 9router windows");
        }
    }
    let names = |p: &str| by_provider[p].keys().cloned().collect::<Vec<_>>();
    assert_eq!(names("anthropic"), [
        "5-hour",
        "weekly",
        "weekly fable",
        "weekly haiku",
        "weekly opus",
        "weekly opus 4",
        "weekly sonnet"
    ]);
    assert_eq!(names("grok-cli"), ["credits", "monthly included", "on-demand", "prepaid", "weekly SuperGrok"]);
    assert_eq!(names("opencode-go"), ["monthly", "rolling", "weekly"]);
}

#[test]
fn testkit_credits_frame_is_9routers_encoding() {
    let g = fixture("grpc-web.json");
    let sample = g["frames"].as_array().unwrap().iter().find(|f| f["name"] == "testkit-sample").unwrap();
    assert_eq!(samples::grok_credits_frame(0.25, 1_759_622_400), hex(sample["hex"].as_str().unwrap()));
    assert_eq!(sample["result"]["percentUsed"], 25);
    assert_eq!(hex(g["empty_request_frame_hex"].as_str().unwrap()), [0u8; 5], "the fallback's request body");
}

#[test]
fn quota_requests_match_the_research_table() {
    // Research R11's endpoints and headers, as 9router sends them.
    let claude = &fixture("quota-claude.json")["cases"][0]["requests"][0];
    assert_eq!(claude["url"], "https://api.anthropic.com/api/oauth/usage");
    assert_eq!(claude["headers"]["anthropic-beta"], "oauth-2025-04-20");
    let grok = fixture("quota-grok-cli.json");
    let flow = grok["flow"].as_array().unwrap();
    let fallback = flow.iter().find(|c| c["name"] == "grpc-fallback").unwrap();
    let urls: Vec<&str> = fallback["requests"].as_array().unwrap().iter().map(|r| r["url"].as_str().unwrap()).collect();
    assert_eq!(urls, [
        "https://cli-chat-proxy.grok.com/v1/billing?format=credits",
        "https://cli-chat-proxy.grok.com/v1/user?include=subscription",
        "https://grok.com/grok_api_v2.GrokBuildBilling/GetGrokCreditsConfig",
    ]);
    assert_eq!(fallback["requests"][2]["headers"]["content-type"], "application/grpc-web+proto");
    for c in fixture("quota-opencode.json")["cases"].as_array().unwrap() {
        if let Some(r) = c["requests"].as_array().unwrap().first() {
            let want = if c["provider"] == "opencode-go" {
                "https://opencode.ai/zen/go/v1/usage"
            } else {
                "https://opencode.ai/zen/v1/usage"
            };
            assert_eq!(r["url"], want);
        }
    }
    // xai has no reader in 9router: "quota not reported" (R11).
    let d = fixture("dispatch.json");
    let supported: Vec<&str> = d["cases"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|c| c["supported"] == true)
        .map(|c| c["ours"].as_str().unwrap())
        .collect();
    assert_eq!(supported, ["anthropic", "grok-cli", "opencode-go", "opencode-zen"]);
}

// ── Ignored until the quota tasks land ───────────────────────────────────────

/// T071: `quota::grpc_web::decode(bytes: &[u8]) -> Option<Ratio>` with
/// `Ratio { percent_used: f64, resets_at: Option<SystemTime> }`: every `grpc-web.json` frame
/// gives 9router's `percentUsed` (within 1e-4) and `resetAt` (RFC 3339, millisecond
/// precision), or `None` where 9router returns null.
#[test]
#[ignore = "T070/T071: quota extractor and gRPC-web decoder not built yet"]
fn grpc_web_frames_decode_like_9router() {
    let frames = fixture("grpc-web.json")["frames"].as_array().unwrap().len();
    assert_eq!(frames, 16);
    todo!("T071: decode each frame's hex and compare with result");
}

/// T070: `quota::extract::windows(&QuotaDecl, &Value) -> Vec<QuotaWindow>` over each bundled
/// plugin's `[quota]` (T074): for every 200 response in `quota-claude.json`,
/// `quota-grok-cli.json` (`parse`, billing and user merged as the plugin declares) and
/// `quota-opencode.json`, the windows equal 9router's quotas under [`our_name`]: `used`,
/// `limit` = `total`, remaining, `resets_at` = `resetAt`. Responses where 9router reports a
/// message and no quotas give no windows.
#[test]
#[ignore = "T070/T071: quota extractor and gRPC-web decoder not built yet"]
fn extracted_windows_match_9router() {
    assert_eq!(windows().len(), 40);
    todo!("T070/T074: run the bundled [quota] rules over each case's response");
}

/// T070: the `auto` reset format parses each `reset-time.json` input to its `result`
/// (seconds below 1e12, else milliseconds; numeric strings alike; RFC 3339; empty, null and 0
/// are no reset).
#[test]
#[ignore = "T070/T071: quota extractor and gRPC-web decoder not built yet"]
fn reset_times_parse_like_9router() {
    assert_eq!(fixture("reset-time.json")["cases"].as_array().unwrap().len(), 12);
    todo!("T070: parse each input with resets_format = auto");
}

/// T076: the grok-cli `[models_live]` paths read `models-grok-cli.json`'s bodies to the same
/// ids, names, context and max output; a 401 refreshes once and retries with the new token.
#[test]
#[ignore = "T076: live model list not built yet"]
fn grok_cli_live_models_match_9router() {
    assert_eq!(fixture("models-grok-cli.json")["flow"].as_array().unwrap().len(), 1);
    todo!("T076: read each body through the [models_live] paths");
}
