//! Quota parity with 9router (spec 005 T040, Constitution VI): the fixtures in
//! `tests/fixtures/9router/usage/` (`quota-*.json`, `grpc-web.json`, `reset-time.json`,
//! `dispatch.json`, `models-grok-cli.json`), generated by `tools/gen-bundled/oauth-oracle.mjs`
//! from 9router's usage readers. `usage/cases.json` (token counts) belongs to slice 003.
//!
//! Live: the fixtures load with the expected cases, the windows 9router reports keep the
//! extractor's invariants, the testkit's gRPC-web sample is byte-identical to 9router's
//! encoder, 0router's window names map one-to-one onto 9router's, and the extractor (T070) and
//! gRPC-web decoder (T071) read every fixture as 9router does, bar the listed deviations.
//!
//! The bundled plugins' `[quota]` and `[models_live]` sections are what is held to 9router
//! (T074, T076).

use std::collections::BTreeMap;

use nullrouter_engine::models_live;
use nullrouter_engine::quota::{self, QuotaWindow, extract, grpc_web};
use nullrouter_engine::testkit::mock_quota::samples;
use nullrouter_registry::schema::{ModelType, QuotaDecl, ResetsFormat};
use serde_json::Value;

fn fixture(name: &str) -> Value {
    let path = format!("{}/../../tests/fixtures/9router/usage/{name}", env!("CARGO_MANIFEST_DIR"));
    let text =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{path}: {e}; run tools/gen-bundled/generate.mjs"));
    let v: Value = serde_json::from_str(&text).unwrap();
    assert!(v["source"].as_str().unwrap().starts_with("Generated from ref/9router@"));
    v["data"].clone()
}

fn hex(s: &str) -> Vec<u8> {
    (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap()).collect()
}

/// 0router's window name (research R11) for 9router's quota key, per provider.
fn our_name(provider: &str, theirs: &str) -> String {
    match provider {
        "anthropic" => match theirs {
            "session (5h)" => "5-hour".into(),
            "weekly (7d)" => "weekly".into(),
            t => t.strip_suffix(" (7d)").unwrap_or(t).to_owned(),
        },
        "opencode-go" | "opencode-zen" => theirs.to_lowercase(),
        _ => match theirs {
            "Weekly SuperGrok" => "weekly SuperGrok".into(),
            t => t.to_lowercase(),
        },
    }
}

/// Every quota window 9router reports, by case: `(case, provider, name, window)`.
fn windows() -> Vec<(String, String, String, Value)> {
    let mut out = Vec::new();
    let mut push = |case: &str, provider: &str, result: &Value| {
        if let Some(q) = result["quotas"].as_object() {
            for (k, w) in q {
                out.push((case.to_owned(), provider.to_owned(), k.clone(), w.clone()));
            }
        }
    };
    for c in fixture("quota-claude.json")["cases"].as_array().unwrap() {
        push(c["name"].as_str().unwrap(), "anthropic", &c["result"]);
    }
    let grok = fixture("quota-grok-cli.json");
    for c in grok["parse"].as_array().unwrap().iter().chain(grok["flow"].as_array().unwrap()) {
        push(c["name"].as_str().unwrap(), "grok-cli", &c["result"]);
    }
    for c in fixture("quota-opencode.json")["cases"].as_array().unwrap() {
        push(c["name"].as_str().unwrap(), c["provider"].as_str().unwrap(), &c["result"]);
    }
    out
}

#[test]
fn fixtures_load_with_every_case() {
    assert_eq!(fixture("quota-claude.json")["cases"].as_array().unwrap().len(), 4);
    let grok = fixture("quota-grok-cli.json");
    assert_eq!((grok["parse"].as_array().unwrap().len(), grok["flow"].as_array().unwrap().len()), (10, 9));
    assert_eq!(fixture("quota-opencode.json")["cases"].as_array().unwrap().len(), 20);
    let g = fixture("grpc-web.json");
    assert_eq!((g["frames"].as_array().unwrap().len(), g["headers"].as_array().unwrap().len()), (16, 7));
    assert_eq!(fixture("reset-time.json")["cases"].as_array().unwrap().len(), 12);
    assert_eq!(fixture("dispatch.json")["cases"].as_array().unwrap().len(), 8);
    assert_eq!(fixture("models-grok-cli.json")["parse"].as_array().unwrap().len(), 3);
    assert_eq!(windows().len(), 40);
}

/// What the extractor will be held to: a percent window has total 100 and remaining
/// `100 - used` floored at 0; a counted window has remaining `total - used` (as a percentage
/// of total); a reset is an RFC 3339 instant or absent.
#[test]
fn reported_windows_keep_the_extractors_invariants() {
    for (case, provider, name, w) in windows() {
        let used = w["used"].as_f64().unwrap();
        let total = w["total"].as_f64().unwrap();
        let pct = w["remainingPercentage"].as_f64().unwrap();
        assert_eq!(w["unlimited"], false, "{case} {name}");
        assert!(total > 0.0, "{case} {name}");
        // 9router's one inconsistent row: a credits bag with only `balance: 0` becomes a
        // synthetic "0 used of 1, 0% left" bar (grok-cli.js:272-279). The extractor reports
        // what the provider said instead: remaining 0.
        if (case.as_str(), used, total) != ("credits-bag-balance-only", 0.0, 1.0) {
            let want = ((total - used).max(0.0) / total) * 100.0;
            assert!((pct - want).abs() < 1e-9, "{case} {provider} {name}: {pct} vs {want}");
        }
        if let Some(r) = w["remaining"].as_f64() {
            assert_eq!(total, 100.0, "{case} {name}: only percent windows carry `remaining`");
            assert!((r - (100.0 - used).max(0.0)).abs() < 1e-9, "{case} {name}");
        }
        match &w["resetAt"] {
            Value::Null => {}
            Value::String(s) => assert!(s.ends_with('Z') && s.len() == 24, "{case} {name}: {s}"),
            v => panic!("{case} {name}: {v}"),
        }
    }
}

#[test]
fn window_names_map_one_to_one() {
    let mut by_provider: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();
    for (_, provider, theirs, _) in windows() {
        let ours = our_name(&provider, &theirs);
        let seen = by_provider.entry(provider.clone()).or_default();
        if let Some(prev) = seen.insert(ours.clone(), theirs.clone()) {
            assert_eq!(prev, theirs, "{provider}: {ours} would merge two 9router windows");
        }
    }
    let names = |p: &str| by_provider[p].keys().cloned().collect::<Vec<_>>();
    assert_eq!(
        names("anthropic"),
        ["5-hour", "weekly", "weekly fable", "weekly haiku", "weekly opus", "weekly opus 4", "weekly sonnet"]
    );
    assert_eq!(names("grok-cli"), ["credits", "monthly included", "on-demand", "prepaid", "weekly SuperGrok"]);
    assert_eq!(names("opencode-go"), ["monthly", "rolling", "weekly"]);
}

#[test]
fn testkit_credits_frame_is_9routers_encoding() {
    let g = fixture("grpc-web.json");
    let sample = g["frames"].as_array().unwrap().iter().find(|f| f["name"] == "testkit-sample").unwrap();
    assert_eq!(samples::grok_credits_frame(0.25, 1_759_622_400), hex(sample["hex"].as_str().unwrap()));
    assert_eq!(sample["result"]["percentUsed"], 25);
    assert_eq!(hex(g["empty_request_frame_hex"].as_str().unwrap()), [0u8; 5], "the fallback's request body");
}

#[test]
fn quota_requests_match_the_research_table() {
    // Research R11's endpoints and headers, as 9router sends them.
    let claude = &fixture("quota-claude.json")["cases"][0]["requests"][0];
    assert_eq!(claude["url"], "https://api.anthropic.com/api/oauth/usage");
    assert_eq!(claude["headers"]["anthropic-beta"], "oauth-2025-04-20");
    let grok = fixture("quota-grok-cli.json");
    let flow = grok["flow"].as_array().unwrap();
    let fallback = flow.iter().find(|c| c["name"] == "grpc-fallback").unwrap();
    let urls: Vec<&str> = fallback["requests"].as_array().unwrap().iter().map(|r| r["url"].as_str().unwrap()).collect();
    assert_eq!(
        urls,
        [
            "https://cli-chat-proxy.grok.com/v1/billing?format=credits",
            "https://cli-chat-proxy.grok.com/v1/user?include=subscription",
            "https://grok.com/grok_api_v2.GrokBuildBilling/GetGrokCreditsConfig",
        ]
    );
    assert_eq!(fallback["requests"][2]["headers"]["content-type"], "application/grpc-web+proto");
    for c in fixture("quota-opencode.json")["cases"].as_array().unwrap() {
        if let Some(r) = c["requests"].as_array().unwrap().first() {
            let want = if c["provider"] == "opencode-go" {
                "https://opencode.ai/zen/go/v1/usage"
            } else {
                "https://opencode.ai/zen/v1/usage"
            };
            assert_eq!(r["url"], want);
            // 9router's opencode reader asks for JSON; the bundled plugin declares the same.
            let ours = plugin_quota(c["provider"].as_str().unwrap()).primary.request.headers;
            assert_eq!(ours.get("Accept").map(String::as_str), r["headers"]["accept"].as_str(), "{}", c["provider"]);
        }
    }
    // xai has no reader in 9router: "quota not reported" (R11).
    let d = fixture("dispatch.json");
    let supported: Vec<&str> = d["cases"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|c| c["supported"] == true)
        .map(|c| c["ours"].as_str().unwrap())
        .collect();
    assert_eq!(supported, ["anthropic", "grok-cli", "opencode-go", "opencode-zen"]);
}
// ── The extractor and decoder against 9router ────────────────────────────────

/// The `[quota]` section `plugins/bundled/<id>.toml` declares: the bundled plugins are what
/// these tests hold to 9router. anthropic follows contracts/signin-quota-schema.md; grok-cli
/// mirrors `parseGrokCliBilling`'s reads (`config.x` before `x`), with the gRPC-web fallback.
fn plugin_quota(id: &str) -> QuotaDecl {
    #[derive(serde::Deserialize)]
    struct Doc {
        quota: QuotaDecl,
    }
    toml::from_str::<Doc>(&bundled(id)).unwrap_or_else(|e| panic!("{id}: {e}")).quota
}

fn bundled(id: &str) -> String {
    let path = format!("{}/../../plugins/bundled/{id}.toml", env!("CARGO_MANIFEST_DIR"));
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{path}: {e}"))
}

/// What a poll reads from one response: `None` for no response (network failure).
enum Answer {
    Json(u16, Value),
    Bytes(u16, Vec<u8>),
}

fn answer(r: &Value) -> Option<Answer> {
    if r["network_failure"] == true || r["status"].is_null() {
        return None;
    }
    let status = r["status"].as_u64().unwrap() as u16;
    Some(match r["hex"].as_str() {
        Some(h) => Answer::Bytes(status, hex(h)),
        None => Answer::Json(status, r["body"].clone()),
    })
}

/// The windows a poll yields: the primary source, then the fallback when the primary gives
/// none. A non-200 answer gives no window (the poller classifies it).
fn poll(q: &QuotaDecl, answers: &[Option<Answer>]) -> Vec<QuotaWindow> {
    let body = |a: Option<&Option<Answer>>| match a {
        Some(Some(Answer::Json(200, v))) => Some(serde_json::to_vec(v).unwrap()),
        Some(Some(Answer::Bytes(200, b))) => Some(b.clone()),
        _ => None,
    };
    let Some(primary) = body(answers.first()) else { return Vec::new() };
    let got = quota::read(&q.primary, &primary);
    match (&q.fallback, got.is_empty()) {
        // grok-cli's second answer is the profile read, which the extractor doesn't need.
        (Some(fb), true) => body(answers.get(2)).map(|b| quota::read(fb, &b)).unwrap_or_default(),
        _ => got,
    }
}

/// The window 9router's quota becomes: `(used, limit, remaining, resets_at)`.
type Want = (Option<f64>, Option<f64>, Option<f64>, Option<String>);

fn want(w: &Value) -> Want {
    let (used, total) = (w["used"].as_f64().unwrap(), w["total"].as_f64().unwrap());
    (Some(used), Some(total), Some((total - used).max(0.0)), w["resetAt"].as_str().map(str::to_owned))
}

/// 9router rows the extractor deliberately reports differently (research R12, R19):
/// `Some(window)` replaces 9router's, `None` drops it.
fn deviation(case: &str, ours: &str, theirs: Want) -> Option<Option<Want>> {
    Some(match (case, ours) {
        // A zero on-demand cap is no window; 9router draws a synthetic "1 used of 1" bar for
        // free accounts and nothing for subscribers, which only the profile read tells apart.
        // 0router tries the gRPC-web pool instead.
        ("exhausted-free", "on-demand") => None,
        // The fixture's sample carries `monthlyUsed`, a field 9router never reads, so 9router
        // counts 0 used. An unresolved `used` skips the window (the testkit now sends
        // `includedUsed`).
        ("testkit-sample", "monthly included") => None,
        // `{ balance: 0 }`: 9router's synthetic "0 of 1"; the extractor reports remaining 0.
        // Likewise a bag with only `remaining > 0` and no total: 9router draws "0 used of
        // <remaining>", the extractor a remaining-only window (parity audit finding 14; no
        // oracle case).
        ("credits-bag-balance-only", "credits") => Some((None, None, Some(0.0), None)),
        // Percent `used` is shown as reported, not capped at 100 (SC-006); 9router caps the
        // anthropic `limits[]` windows and opencode's.
        ("limits-clamped-and-skipped", "weekly opus 4") => Some((Some(140.0), Some(100.0), Some(0.0), theirs.3)),
        ("string-percent-and-clamp", "weekly") => Some((Some(130.0), Some(100.0), Some(0.0), theirs.3)),
        _ => return None,
    })
}

/// Windows the extractor reports where 9router has none: numeric strings are numbers for
/// every provider; 9router's claude reader alone refuses them.
fn extra(case: &str) -> Vec<(&'static str, Want)> {
    let at = |s: &str| Some(s.to_owned());
    match case {
        "utilization-not-a-number" => {
            vec![("5-hour", (Some(87.0), Some(100.0), Some(13.0), at("2026-10-02T18:00:00.000Z")))]
        }
        "limits-clamped-and-skipped" => vec![("weekly sonnet", (Some(50.0), Some(100.0), Some(50.0), None))],
        _ => Vec::new(),
    }
}

fn check(case: &str, provider: &str, theirs: &Value, ours: &[QuotaWindow]) {
    let mut expected: BTreeMap<String, Want> = BTreeMap::new();
    if let Some(q) = theirs["quotas"].as_object() {
        for (k, w) in q {
            let name = our_name(provider, k);
            match deviation(case, &name, want(w)) {
                Some(Some(d)) => expected.insert(name, d),
                Some(None) => None,
                None => expected.insert(name, want(w)),
            };
        }
    }
    for (name, w) in extra(case) {
        expected.insert(name.to_owned(), w);
    }
    let got: BTreeMap<String, Want> = ours
        .iter()
        .map(|w| (w.name.clone(), (w.used, w.limit, w.remaining, w.resets_at.map(extract::rfc3339_millis))))
        .collect();
    assert_eq!(got.len(), ours.len(), "{case}: duplicate window names");
    assert_eq!(got.keys().collect::<Vec<_>>(), expected.keys().collect::<Vec<_>>(), "{case} {provider}");
    let close = |a: Option<f64>, b: Option<f64>| match (a, b) {
        (Some(a), Some(b)) => (a - b).abs() < 1e-9,
        (a, b) => a == b,
    };
    for (name, g) in &got {
        let e = &expected[name];
        assert!(close(g.0, e.0) && close(g.1, e.1) && close(g.2, e.2), "{case} {name}: {g:?} vs {e:?}");
        assert_eq!(g.3, e.3, "{case} {name}: reset");
    }
}

/// T071: every `grpc-web.json` frame gives 9router's `percentUsed` (within 1e-4) and `resetAt`
/// (RFC 3339, millisecond precision), or `None` where 9router returns null.
#[test]
fn grpc_web_frames_decode_like_9router() {
    let frames = fixture("grpc-web.json")["frames"].as_array().unwrap().clone();
    assert_eq!(frames.len(), 16);
    for f in frames {
        let name = f["name"].as_str().unwrap();
        let got = grpc_web::decode(&hex(f["hex"].as_str().unwrap()));
        let want = &f["result"];
        let Some(r) = got else {
            assert!(want.is_null(), "{name}: decoded nothing, 9router read {want}");
            continue;
        };
        assert!(!want.is_null(), "{name}: decoded {r:?}, 9router read nothing");
        assert!((r.percent_used - want["percentUsed"].as_f64().unwrap()).abs() < 1e-4, "{name}: {r:?}");
        assert_eq!(r.resets_at.map(extract::rfc3339_millis).as_deref(), want["resetAt"].as_str(), "{name}");
    }
}

/// T070: for every 200 response in `quota-claude.json`, `quota-grok-cli.json` (`parse` and
/// `flow`, the billing body; the profile read only names the plan) and `quota-opencode.json`,
/// the windows equal 9router's quotas under [`our_name`]: `used`, `limit` = `total`,
/// remaining, `resets_at` = `resetAt`, except the deliberate [`deviation`]s and [`extra`]s.
/// Responses where 9router reports a message and no quotas give no windows.
#[test]
fn extracted_windows_match_9router() {
    assert_eq!(windows().len(), 40);
    let claude = plugin_quota("anthropic");
    for c in fixture("quota-claude.json")["cases"].as_array().unwrap() {
        let ours = poll(&claude, &[answer(&c["input"]["response"])]);
        check(c["name"].as_str().unwrap(), "anthropic", &c["result"], &ours);
    }
    let grok = plugin_quota("grok-cli");
    let g = fixture("quota-grok-cli.json");
    for c in g["parse"].as_array().unwrap() {
        let ours = quota::read(&grok.primary, &serde_json::to_vec(&c["billing"]).unwrap());
        check(c["name"].as_str().unwrap(), "grok-cli", &c["result"], &ours);
    }
    for c in g["flow"].as_array().unwrap() {
        let answers: Vec<_> = c["input"]["responses"].as_array().unwrap().iter().map(answer).collect();
        check(c["name"].as_str().unwrap(), "grok-cli", &c["result"], &poll(&grok, &answers));
    }
    let (go, zen) = (plugin_quota("opencode-go"), plugin_quota("opencode-zen"));
    assert_eq!(go.primary.request.url, "https://opencode.ai/zen/go/v1/usage");
    assert_eq!(zen.primary.request.url, "https://opencode.ai/zen/v1/usage");
    for c in fixture("quota-opencode.json")["cases"].as_array().unwrap() {
        let provider = c["provider"].as_str().unwrap();
        let q = if provider == "opencode-go" { &go } else { &zen };
        let answers: Vec<_> = c["input"]["responses"].as_array().unwrap().iter().map(answer).collect();
        check(c["name"].as_str().unwrap(), provider, &c["result"], &poll(q, &answers));
    }
}

/// T070: the `auto` reset format parses each `reset-time.json` input to its `result`
/// (seconds below 1e12, else milliseconds; numeric strings alike; RFC 3339; empty, null and 0
/// are no reset).
#[test]
fn reset_times_parse_like_9router() {
    let cases = fixture("reset-time.json")["cases"].as_array().unwrap().clone();
    assert_eq!(cases.len(), 12);
    for c in cases {
        let got = extract::parse_reset(&c["input"], ResetsFormat::Auto).map(extract::rfc3339_millis);
        assert_eq!(got.as_deref(), c["result"].as_str(), "{}", c["input"]);
    }
}

// ── The live model list (T076) ───────────────────────────────────────────────

/// T076: the grok-cli `[models_live]` paths read each `models-grok-cli.json` body to 9router's
/// ids, names, context and max output (grok-build's limits from its static `[[models]]` entry,
/// as 9router's constants). The flow case (a 401 refreshes once and retries with the new
/// token) runs against the server in `nullrouter-server/tests/quota_poll.rs`; here, its
/// request carries the declared headers and its final body reads to 9router's result.
#[test]
fn grok_cli_live_models_match_9router() {
    let text = bundled("grok-cli");
    let entity = nullrouter_registry::validate_user_plugin(&text, std::path::Path::new("grok-cli.toml"))
        .unwrap_or_else(|e| panic!("{e:#?}"));
    let decl = entity.models_live.clone().expect("grok-cli declares [models_live]");
    let fixture = fixture("models-grok-cli.json");
    let statics = |m| models_live::with_static_limits(&entity, m);
    let as_9router = |m: &[models_live::LiveModel]| -> Vec<(String, String, Option<u64>, Option<u64>)> {
        m.iter().map(|m| (m.id.clone(), m.name.clone(), m.context, m.max_output)).collect()
    };
    let theirs = |result: &Value| -> Vec<(String, String, Option<u64>, Option<u64>)> {
        result
            .as_array()
            .unwrap()
            .iter()
            .map(|m| {
                (
                    m["id"].as_str().unwrap().to_owned(),
                    m["name"].as_str().unwrap().to_owned(),
                    m["contextLength"].as_u64(),
                    m["maxOutputTokens"].as_u64(),
                )
            })
            .collect()
    };
    let cases = fixture["parse"].as_array().unwrap();
    assert_eq!(cases.len(), 3);
    for c in cases {
        let ours = statics(models_live::parse(&decl, &c["body"]));
        assert_eq!(as_9router(&ours), theirs(&c["result"]), "{}", c["name"]);
        assert!(ours.iter().all(|m| m.ty == ModelType::Text));
    }
    let flow = &fixture["flow"].as_array().unwrap()[0];
    let models_req = &flow["requests"][0];
    assert_eq!(models_req["url"], decl.url.as_str());
    for (k, v) in &decl.headers {
        assert_eq!(models_req["headers"][k.to_ascii_lowercase()], v.as_str(), "{k}");
    }
    let last = &flow["responses"].as_array().unwrap()[2]["body"];
    let ours = statics(models_live::parse(&decl, last));
    assert_eq!(as_9router(&ours), theirs(&flow["result"]["models"]));
}
