//! Sign-in parity with 9router (spec 005 T040, Constitution VI): the fixtures in
//! `tests/fixtures/9router/oauth/`, generated by `tools/gen-bundled/oauth-oracle.mjs` from
//! 9router's own sign-in and refresh modules.
//!
//! Live: the bundled plugins' `[signin]` data, authorize URLs, code-exchange and device-grant
//! bodies (driven through the real flows against the mock identity provider), refresh request
//! shape, and token-endpoint error codes with their transient/permanent split. Deliberate
//! deviations (research R19, and the ones this file names) are asserted as deviations.
//!
//! Also live since US2: the refresh call (T050), its classification (T051) and the
//! maintenance queue's selection (T054).

use std::collections::{BTreeMap, BTreeSet};
use std::time::Duration;

use std::time::SystemTime;

use nullrouter_engine::accounts::{Account, SecretSource};
use nullrouter_engine::maintenance;
use nullrouter_engine::signin::classify::{RefreshClass, classify};
use nullrouter_engine::signin::refresh::Timing;
use nullrouter_engine::signin::{self, Begun, SignInError, SignInHttp, encode_body, pkce};
use nullrouter_engine::testkit::mock_idp::{AUTHORIZE, DEVICE, DISCOVERY, PROFILE, TOKEN};
use nullrouter_engine::testkit::{MockIdp, MockUpstream, Step};
use nullrouter_engine::tokens::{AccountState, TokenEntry, TokenView};
use nullrouter_registry::schema::{RedirectKind, SignInDecl, SignInFlow, TokenBody};
use nullrouter_registry::validate::validate_with;
use nullrouter_registry::{PluginSource, ProviderEntity, SecretString};
use serde_json::{Value, json};
use tokio_util::sync::CancellationToken;

fn fixture(name: &str) -> Value {
    let path = format!("{}/../../tests/fixtures/9router/oauth/{name}", env!("CARGO_MANIFEST_DIR"));
    let text =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{path}: {e}; run tools/gen-bundled/generate.mjs"));
    let v: Value = serde_json::from_str(&text).unwrap();
    assert!(v["source"].as_str().unwrap().starts_with("Generated from ref/9router@"));
    v["data"].clone()
}

fn bundled_src(id: &str) -> String {
    std::fs::read_to_string(format!("{}/../../plugins/bundled/{id}.toml", env!("CARGO_MANIFEST_DIR"))).unwrap()
}

fn entity(id: &str, src: &str, allow_private: bool) -> ProviderEntity {
    let ctx = nullrouter_registry::bundled_gate_ctx(false, allow_private).unwrap();
    validate_with(src, PluginSource::Bundled, &format!("{id}.toml"), &ctx)
        .unwrap_or_else(|e| panic!("{id}: {e:#?}"))
        .entity
}

fn decl(id: &str) -> SignInDecl {
    entity(id, &bundled_src(id), false).signin.unwrap_or_else(|| panic!("{id} has [signin]"))
}

/// The bundled plugin with its sign-in URLs moved to the mock identity provider. Redirects
/// stay as declared.
fn at_mock(idp: &MockIdp, id: &str) -> ProviderEntity {
    let d = decl(id);
    let mut src = bundled_src(id);
    let mut swap = |from: Option<&str>, to: &str| {
        if let Some(from) = from {
            src = src.replace(&format!("\"{from}\""), &format!("\"{}\"", idp.url(to)));
        }
    };
    swap(d.discovery_url.as_deref(), DISCOVERY);
    swap(d.authorize_url.as_deref(), AUTHORIZE);
    swap(Some(&d.token_url), TOKEN);
    swap(d.device_url.as_deref(), DEVICE);
    swap(d.profile.as_ref().map(|p| p.url.as_str()), PROFILE);
    idp.set_client_id(&d.client_id);
    entity(id, &src, true)
}

fn strs(v: &Value) -> Vec<String> {
    v.as_array().unwrap().iter().map(|s| s.as_str().unwrap().to_owned()).collect()
}

/// A recorded body's field names and values.
fn fields(body: &Value) -> BTreeMap<String, String> {
    body["fields"]
        .as_array()
        .unwrap()
        .iter()
        .map(|kv| (kv[0].as_str().unwrap().to_owned(), kv[1].as_str().unwrap().to_owned()))
        .collect()
}

fn encoding(kind: TokenBody) -> &'static str {
    match kind {
        TokenBody::Form => "form",
        TokenBody::Json => "json",
    }
}

fn http() -> SignInHttp {
    SignInHttp::new(true).with_timeout(Duration::from_secs(5))
}

#[test]
fn bundled_signin_declarations_match_9router() {
    let data = fixture("providers.json");
    for (id, want) in data["providers"].as_object().unwrap() {
        let d = decl(id);
        assert_eq!(d.client_id, want["client_id"].as_str().unwrap(), "{id} client_id");
        assert_eq!(d.scopes, strs(&want["scopes"]), "{id} scopes");
        assert_eq!(d.token_url, want["token_url"].as_str().unwrap(), "{id} token_url");
        assert_eq!(encoding(d.body), want["token_body"].as_str().unwrap(), "{id} token body");
        assert_eq!(d.refresh_lead.as_millis(), u128::from(want["refresh_lead_ms"].as_u64().unwrap()), "{id} lead");
        match want["flow"].as_str().unwrap() {
            "device_code" => {
                assert_eq!(d.flow, SignInFlow::DeviceCode, "{id}");
                assert_eq!(d.device_url.as_deref(), want["device_url"].as_str(), "{id} device_url");
                if let Some(r) = want.get("refresh_url") {
                    assert_eq!(Some(d.token_url.as_str()), r.as_str(), "{id}: refresh goes to the token URL");
                }
                for (k, v) in want["params"].as_object().unwrap() {
                    let ours = d.params.iter().find(|(p, _)| format!("{p:?}").eq_ignore_ascii_case(k));
                    let ours = ours.map(|(_, v)| pkce::param_value(v));
                    assert_eq!(ours.as_deref(), v.as_str(), "{id} param {k}");
                }
            }
            _ => {
                assert_eq!(d.flow, SignInFlow::Pkce, "{id}");
                assert_eq!(d.authorize_url.as_deref(), want["authorize_url"].as_str(), "{id} authorize_url");
                assert_eq!(d.discovery_url.as_deref(), want["discovery_url"].as_str(), "{id} discovery_url");
                assert_eq!(u64::from(d.verifier_len()), want["verifier_bytes"].as_u64().unwrap(), "{id} verifier");
            }
        }
    }

    // grok-cli: the official CLI's pager agent (`grok-cli.js` device request and polls).
    assert_eq!(
        decl("grok-cli").headers.get("User-Agent").map(String::as_str),
        Some("grok-pager/0.2.93 grok-shell/0.2.93 (linux; x86_64)")
    );
    assert!(decl("xai").headers.is_empty() && decl("anthropic").headers.is_empty());

    // xai: the same loopback redirect.
    let xai = decl("xai");
    assert_eq!(xai.redirect[0].uri, data["providers"]["xai"]["redirect_uri"].as_str().unwrap());
    assert_eq!(xai.redirect[0].kind, RedirectKind::Loopback);
    // Deviation (R19, R4): 9router's claude sign-in has only the dashboard's localhost
    // redirect; 0router offers Anthropic's hosted code page first, loopback second.
    let anthropic = decl("anthropic");
    assert!(data["providers"]["anthropic"]["redirect_uri"].is_null());
    assert_eq!(
        anthropic.redirect.iter().map(|r| r.kind).collect::<Vec<_>>(),
        [RedirectKind::CodePage, RedirectKind::Loopback]
    );
}

/// Query pairs, decoded, with a 32-hex nonce as 9router's oracle records it.
fn decoded_pairs(url: &str) -> (String, Vec<(String, String)>) {
    let u = url::Url::parse(url).unwrap();
    let base = format!("{}://{}{}", u.scheme(), u.host_str().unwrap(), u.path());
    let mut pairs: Vec<(String, String)> = u
        .query_pairs()
        .map(|(k, v)| {
            let hex = v.len() == 32 && v.chars().all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase());
            (k.clone().into_owned(), if k == "nonce" && hex { "{random.hex16}".into() } else { v.into_owned() })
        })
        .collect();
    pairs.sort();
    (base, pairs)
}

#[test]
fn authorize_urls_match_9router() {
    let data = fixture("authorize.json");
    let mut seen = 0;
    for c in data["cases"].as_array().unwrap() {
        let name = c["name"].as_str().unwrap();
        let id = c["provider"].as_str().unwrap();
        let d = decl(id);
        if let Some(len) = c.get("verifier_len") {
            // generateAuthData: verifier and state lengths.
            assert_eq!(pkce::verifier(d.verifier_len()).len() as u64, len.as_u64().unwrap(), "{name}");
            assert_eq!(pkce::state().len() as u64, c["state_len"].as_u64().unwrap(), "{name}");
            continue;
        }
        let input = &c["input"];
        let ours = pkce::authorize_url(
            c["base"].as_str().unwrap(),
            &d,
            input["redirect_uri"].as_str().unwrap(),
            input["challenge"].as_str().unwrap(),
            input["state"].as_str().unwrap(),
        );
        let (base, pairs) = decoded_pairs(&ours);
        assert_eq!(base, c["base"].as_str().unwrap(), "{name}");
        let mut want: Vec<(String, String)> = c["params"]
            .as_array()
            .unwrap()
            .iter()
            .map(|kv| (kv[0].as_str().unwrap().to_owned(), kv[1].as_str().unwrap().to_owned()))
            .collect();
        want.sort();
        assert_eq!(pairs, want, "{name}: same parameters and values (order is not significant)");

        let query = c["query"].as_str().unwrap();
        if query.contains("scope=org%3Acreate_api_key+user") {
            // Deviation: 9router's claude URL comes from URLSearchParams (space as `+`); 0router
            // encodes every authorize URL like encodeURIComponent (`%20`), as 9router's xai does.
            // Both decode to the same scope.
            assert!(ours.contains("scope=org%3Acreate_api_key%20user%3Aprofile%20user%3Ainference"), "{ours}");
        } else {
            assert!(ours.contains(query.split('&').find(|p| p.starts_with("scope=")).unwrap()), "{name}: {ours}");
        }
        seen += 1;
    }
    assert_eq!(seen, 3);
}

#[tokio::test]
async fn xai_code_exchange_sends_9routers_form_body() {
    let want = fixture("token-requests.json")["cases"]
        .as_array()
        .unwrap()
        .iter()
        .find(|c| c["name"] == "xai-code-exchange")
        .unwrap()
        .clone();
    let idp = MockIdp::start().await;
    idp.set_id_claims(Some(json!({ "email": want["result"]["email"], "sub": "s-2" })));
    let p = at_mock(&idp, "xai");
    let Begun::Pkce(mut s) = signin::begin(&http(), &p).await.unwrap() else { panic!("xai is pkce") };
    let location = idp.browse(s.authorize_url()).await;
    let code = s.wait_code(async move { Some(location) }, &CancellationToken::new()).await.unwrap();
    let e = s.complete(&http(), "main", code).await.unwrap();

    let sent = idp.token_requests().pop().unwrap();
    // calls[0] is discovery (as 0router does it), then the exchange at the discovered URL.
    assert!(want["calls"][0]["url"].as_str().unwrap().ends_with("/.well-known/openid-configuration"));
    let call = &want["calls"][1];
    assert_eq!(call["body"]["encoding"], if sent.json { "json" } else { "form" });
    let theirs = fields(&call["body"]);
    assert_eq!(sent.fields.keys().collect::<BTreeSet<_>>(), theirs.keys().collect::<BTreeSet<_>>());
    for k in ["grant_type", "client_id"] {
        assert_eq!(sent.get(k), theirs.get(k).map(String::as_str), "{k}");
    }
    assert_eq!(sent.get("redirect_uri"), Some(s.redirect_uri()));
    assert_eq!(sent.get("code_verifier").unwrap().len(), 128, "96-byte verifier, as 9router");
    // 9router's mapTokens reads the email from the id token; so does 0router (no profile).
    assert_eq!(e.claims.email.as_deref(), want["result"]["email"].as_str());
}

#[tokio::test]
async fn anthropic_code_exchange_sends_9routers_json_body() {
    let cases = fixture("token-requests.json");
    let want = cases["cases"].as_array().unwrap().iter().find(|c| c["name"] == "anthropic-code-exchange").unwrap();
    let idp = MockIdp::start().await;
    let p = at_mock(&idp, "anthropic");
    let Begun::Pkce(mut s) = signin::begin(&http(), &p).await.unwrap() else { panic!("anthropic is pkce") };
    // The hosted code page is the first redirect (R19); the operator pastes its address.
    assert_eq!(s.redirect_kind(), RedirectKind::CodePage);
    let location = idp.browse(s.authorize_url()).await;
    let code = s.wait_code(async move { Some(location) }, &CancellationToken::new()).await.unwrap();
    s.complete(&http(), "main", code).await.unwrap();

    let sent = idp.token_requests().pop().unwrap();
    let call = &want["calls"][0];
    assert_eq!(call["headers"]["content-type"], "application/json");
    assert!(sent.json, "JSON body, as 9router");
    let theirs = fields(&call["body"]);
    assert_eq!(sent.fields.keys().collect::<BTreeSet<_>>(), theirs.keys().collect::<BTreeSet<_>>());
    assert_eq!(sent.get("grant_type"), Some("authorization_code"));
    assert_eq!(sent.get("client_id"), theirs.get("client_id").map(String::as_str));
    assert!(sent.get("state").is_some_and(|st| !st.is_empty()), "state travels in the JSON body");
    // 9router splits a pasted `code#state` and sends the page's state.
    let split = cases["cases"].as_array().unwrap().iter().find(|c| c["name"] == "anthropic-code-hash-state").unwrap();
    let f = fields(&split["calls"][0]["body"]);
    assert_eq!((f["code"].as_str(), f["state"].as_str()), ("auth-code", "state-from-page"));
    let pasted = s.parse_paste("auth-code#nope");
    assert!(pasted.is_err(), "0router checks a pasted state instead of sending it on");
}

#[tokio::test]
async fn grok_cli_device_grant_sends_9routers_bodies() {
    let cases = fixture("token-requests.json");
    let by = |n: &str| cases["cases"].as_array().unwrap().iter().find(|c| c["name"] == n).unwrap().clone();
    let idp = MockIdp::start().await;
    let p = at_mock(&idp, "grok-cli");
    let Begun::Device(mut d) = signin::begin(&http(), &p).await.unwrap() else { panic!("grok-cli is device code") };
    d.poll(&http(), "main", &CancellationToken::new()).await.unwrap();

    let device = idp.device_requests().pop().unwrap();
    let want = fields(&by("grok-cli-device-request")["calls"][0]["body"]);
    assert!(!device.json);
    assert_eq!(device.fields, want, "client_id, scope (all eight) and referrer=grok-build");

    // The official CLI's pager agent on the device request and every token poll
    // (`[signin] headers`); the profile read carries 9router's agent and client version.
    let header = |h: &reqwest::header::HeaderMap, k: &str| h.get(k).and_then(|v| v.to_str().ok()).map(str::to_owned);
    let theirs = &by("grok-cli-device-request")["calls"][0]["headers"];
    let ua = theirs["user-agent"].as_str().unwrap();
    assert_eq!(ua, "grok-pager/0.2.93 grok-shell/0.2.93 (linux; x86_64)");
    assert_eq!(header(&idp.headers_at(DEVICE).pop().unwrap(), "user-agent").as_deref(), Some(ua));
    let polls = idp.headers_at(TOKEN);
    assert!(!polls.is_empty() && polls.iter().all(|h| header(h, "user-agent").as_deref() == Some(ua)), "every poll");
    for h in idp.headers_at(DEVICE).iter().chain(&polls) {
        assert_eq!(header(h, "accept").as_deref(), theirs["accept"].as_str());
        assert_eq!(header(h, "content-type").as_deref(), theirs["content-type"].as_str());
    }
    let profile = &by("grok-cli-device-granted")["calls"][1]["headers"];
    let ours = idp.headers_at(PROFILE).pop().expect("the profile was read");
    for k in ["user-agent", "x-grok-client-version", "x-xai-token-auth", "accept"] {
        assert_eq!(header(&ours, k).as_deref(), profile[k].as_str(), "profile {k}");
    }

    let poll = idp.token_requests().pop().unwrap();
    let want = fields(&by("grok-cli-device-granted")["calls"][0]["body"]);
    assert!(!poll.json);
    assert_eq!(poll.fields.keys().collect::<BTreeSet<_>>(), want.keys().collect::<BTreeSet<_>>());
    assert_eq!(poll.get("grant_type"), want.get("grant_type").map(String::as_str));
    assert_eq!(poll.get("client_id"), want.get("client_id").map(String::as_str));

    // 9router's poll outcomes: pending and slow_down keep waiting, the rest end the sign-in.
    for (n, pending) in [("grok-cli-device-pending", true), ("grok-cli-device-slow-down", false)] {
        let r = &by(n)["result"];
        assert_eq!((r["success"].as_bool(), r["pending"].as_bool()), (Some(false), Some(pending)), "{n}");
    }
    for n in ["grok-cli-device-expired", "grok-cli-device-denied"] {
        assert!(by(n)["result"].get("pending").is_none(), "{n} ends the sign-in");
    }
}

/// The refresh request 9router sends: the provider's token URL and encoding, and exactly
/// `grant_type=refresh_token`, `refresh_token`, `client_id` (T050 builds the same).
#[test]
fn refresh_requests_use_the_declared_token_url_encoding_and_fields() {
    let data = fixture("refresh.json");
    let cases = data["cases"].as_array().unwrap();
    assert_eq!(cases.len(), 6);
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let d = decl(c["provider"].as_str().unwrap());
        let call = &c["calls"][0];
        assert_eq!(call["url"].as_str(), Some(d.token_url.as_str()), "{name}");
        let (ct, _) = encode_body(d.body, &[]);
        assert_eq!(call["headers"]["content-type"].as_str(), Some(ct), "{name}");
        let f = fields(&call["body"]);
        assert_eq!(
            f.keys().map(String::as_str).collect::<BTreeSet<_>>(),
            BTreeSet::from(["client_id", "grant_type", "refresh_token"])
        );
        assert_eq!(
            (f["grant_type"].as_str(), f["client_id"].as_str()),
            ("refresh_token", d.client_id.as_str()),
            "{name}"
        );
        assert_eq!(f["refresh_token"], c["input"]["refresh_token"].as_str().unwrap(), "{name}");
        // Rotation (research R9, providers.js:131): the old refresh token stays when the
        // response has none.
        let kept = c["result"]["refreshToken"].as_str().unwrap();
        let want =
            c["response"]["refresh_token"].as_str().unwrap_or_else(|| c["input"]["refresh_token"].as_str().unwrap());
        assert_eq!(kept, want, "{name}");
    }
    // Without a refresh token nothing is sent.
    assert!(data["guards"].as_array().unwrap().iter().all(|g| g["result"].is_null() && g["calls"] == 0));
}

/// Research R10's class of a token-endpoint failure: `None` where R10 says nothing (404).
fn r10_permanent(status: Option<u64>) -> Option<bool> {
    match status {
        None => Some(false),
        Some(400 | 401 | 403) => Some(true),
        Some(429 | 500..=599) => Some(false),
        Some(_) => None,
    }
}

/// Every refresh-error case answered by a mock token endpoint and read by 0router's token
/// request: the error code 9router's classifier reads, and the transient/permanent split.
#[tokio::test]
async fn refresh_errors_read_9routers_codes_and_split_like_r10() {
    let data = fixture("refresh-errors.json");
    let cases = data["cases"].as_array().unwrap();
    assert_eq!(cases.len(), 15);
    let mock = MockUpstream::start().await;
    let body =
        encode_body(TokenBody::Form, &[("grant_type", "refresh_token"), ("refresh_token", "r"), ("client_id", "c")]);
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let status = c["status"].as_u64();
        let url = match status {
            Some(s) => {
                let s = u16::try_from(s).unwrap();
                mock.push([match &c["body"] {
                    Value::String(t) => Step::Reply { status: s, headers: vec![], body: t.clone().into() },
                    v => Step::json(s, v.clone()),
                }]);
                mock.url("/oauth2/token")
            }
            // A closed port: connection failure.
            None => format!("http://127.0.0.1:{}/oauth2/token", closed_port()),
        };
        let err = signin::token_request(&http(), &url, Default::default(), body.clone()).await.unwrap_err();

        if let Some(permanent) = r10_permanent(status) {
            assert_eq!(err.is_transient(), !permanent, "{name}: {err}");
        }
        match (&err, &c["classify"]["code"]) {
            (SignInError::Rejected { code, .. }, Value::String(theirs)) if !theirs.is_empty() => {
                // `error`, then `error_code`, as 9router's classifier reads them (R10).
                assert_eq!(code, theirs, "{name}");
            }
            (SignInError::Rejected { code, status: s, .. }, _) => assert_eq!(code, &format!("HTTP {s}"), "{name}"),
            (SignInError::Transport { .. }, _) => assert!(status.is_none(), "{name}"),
            (other, _) => panic!("{name}: {other}"),
        }

        // Deviation (R19, FR-015): 9router's claude refresh returns null for every failure and
        // its xai/grok-cli refresh flags only invalid_grant/invalid_request, so a dead refresh
        // token is retried forever. 0router reads every 400/401/403 as permanent.
        assert_eq!(c["refresh"]["anthropic"]["unrecoverable"], false, "{name}");
        let flagged = c["refresh"]["xai"]["unrecoverable"].as_bool().unwrap();
        assert_eq!(flagged, matches!(name, "invalid-grant" | "invalid-request" | "error-code-field"), "{name}");
        assert_eq!(c["refresh"]["grok-cli"], c["refresh"]["xai"], "{name}: grok-cli refreshes like xai");
        if status.is_some_and(|s| matches!(s, 400 | 401 | 403)) {
            assert!(!err.is_transient(), "{name}: permanent in 0router whatever 9router does");
        }
    }
}

fn closed_port() -> u16 {
    let l = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
    l.local_addr().unwrap().port()
}

/// 9router's background refresher selects a token within max(lead, 30 min) of expiry; so
/// does 0router's maintenance queue (research R9), with a ceiling of half the token's
/// lifetime that a long-lived token never reaches.
#[test]
fn maintenance_selects_accounts_due_for_refresh() {
    let data = fixture("refresh-schedule.json");
    let cases = data["cases"].as_array().unwrap();
    assert_eq!(cases.len(), 33);
    let timing = Timing::default();
    let now = SystemTime::now();
    let mut checked = 0;
    for c in cases {
        let (id, name) = (c["provider"].as_str().unwrap(), c["name"].as_str().unwrap());
        let d = decl(id);
        // 0router always knows an expiry: a token response without `expires_in` gets the
        // default hour (DEFAULT_EXPIRES_IN), so "no expiry" can't occur.
        let Some(minutes) = c["expires_in_minutes"].as_i64() else { continue };
        let account = match c["auth_type"].as_str().unwrap() {
            "oauth" => Account::signin(id, "main", 0),
            _ => Account::key(
                id,
                "main",
                SecretSource::Literal,
                Some(SecretString::new("sk-key-0000")),
                0,
                BTreeSet::new(),
            ),
        };
        let expires_at = if minutes >= 0 {
            now + Duration::from_secs(minutes.unsigned_abs() * 60)
        } else {
            now - Duration::from_secs(minutes.unsigned_abs() * 60)
        };
        let view = TokenView {
            entry: TokenEntry {
                provider: id.into(),
                name: "main".into(),
                access_token: SecretString::new("access-0000"),
                refresh_token: c["has_refresh_token"].as_bool().unwrap().then(|| SecretString::new("refresh-0000")),
                expires_at,
                scope: String::new(),
                claims: Default::default(),
                hosts: BTreeSet::new(),
                // Signed in long ago: the half-lifetime ceiling stays above every lead.
                signed_in_at: now - Duration::from_secs(12 * 3600),
                last_refresh_at: None,
                state: None,
                state_since: None,
                state_reason: None,
            },
            state: AccountState::Active,
            previous: None,
        };
        let ours = maintenance::refresh_time(&account, Some(&view), Some(&d), &timing).is_some_and(|t| t <= now);
        assert_eq!(Some(ours), c["selected"].as_bool(), "{id} {name}");
        checked += 1;
    }
    assert_eq!(checked, 30);
}

/// T050: `signin::refresh::refresh` against the mock identity provider for each
/// `refresh.json` case: the request fields equal 9router's, and the stored refresh token
/// rotates or stays as `result`.
#[tokio::test]
async fn refresh_call_rotates_like_9router() {
    let data = fixture("refresh.json");
    let cases = data["cases"].as_array().unwrap();
    assert_eq!(cases.len(), 6);
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let idp = MockIdp::start().await;
        let p = at_mock(&idp, c["provider"].as_str().unwrap());
        let rotates = c["response"].get("refresh_token").is_some();
        idp.set_rotation(rotates);
        let (access, refresh_token, _) = idp.grant();
        let entry = TokenEntry {
            provider: p.id.clone(),
            name: "main".into(),
            access_token: SecretString::new(access),
            refresh_token: Some(SecretString::new(refresh_token.clone())),
            expires_at: SystemTime::now(),
            scope: "s".into(),
            claims: Default::default(),
            hosts: p.token_hosts(),
            signed_in_at: SystemTime::now(),
            last_refresh_at: None,
            state: None,
            state_since: None,
            state_reason: None,
        };
        let next = signin::refresh::refresh(&http(), &p, &entry).await.unwrap_or_else(|e| panic!("{name}: {e}"));

        let sent = idp.token_requests().pop().unwrap();
        let call = &c["calls"][0];
        assert_eq!(call["body"]["encoding"], if sent.json { "json" } else { "form" }, "{name}");
        // Deviation: 9router's refresh sends no agent; 0router sends the plugin's
        // `[signin] headers` on every sign-in call, refresh included (grok-cli's pager agent).
        let ua = idp.headers_at(TOKEN).pop().unwrap().get("user-agent").map(|v| v.to_str().unwrap().to_owned());
        assert_eq!(ua, p.signin.as_ref().unwrap().headers.get("User-Agent").cloned(), "{name}");
        assert_eq!(call["headers"].get("user-agent"), None, "{name}: 9router sends none");
        let theirs = fields(&call["body"]);
        assert_eq!(sent.fields.keys().collect::<BTreeSet<_>>(), theirs.keys().collect::<BTreeSet<_>>(), "{name}");
        assert_eq!(sent.get("grant_type"), Some("refresh_token"), "{name}");
        assert_eq!(sent.get("client_id"), theirs.get("client_id").map(String::as_str), "{name}");
        assert_eq!(sent.get("refresh_token"), Some(refresh_token.as_str()), "{name}");

        let kept = next.refresh_token.as_ref().unwrap();
        assert!(!next.access_token.matches(&entry.access_token.with_exposed(str::to_owned)), "{name}");
        assert_eq!(!kept.matches(&refresh_token), rotates, "{name}: rotated iff the response carried one");
        assert!(next.last_refresh_at.is_some() && next.expires_at > SystemTime::now(), "{name}");
    }
}

/// T051: `signin::classify::classify` for every `refresh-errors.json` case: Permanent for
/// R10's codes and any other 400/401/403, Transient for 429, 5xx and transport failures.
/// A status R10 doesn't name (404) is transient: an endpoint outage never takes an account
/// out of service.
#[tokio::test]
async fn refresh_failures_classify_per_r10() {
    let data = fixture("refresh-errors.json");
    let cases = data["cases"].as_array().unwrap();
    assert_eq!(cases.len(), 15);
    let mock = MockUpstream::start().await;
    let body =
        encode_body(TokenBody::Form, &[("grant_type", "refresh_token"), ("refresh_token", "r"), ("client_id", "c")]);
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let status = c["status"].as_u64();
        let url = match status {
            Some(s) => {
                let s = u16::try_from(s).unwrap();
                mock.push([match &c["body"] {
                    Value::String(t) => Step::Reply { status: s, headers: vec![], body: t.clone().into() },
                    v => Step::json(s, v.clone()),
                }]);
                mock.url("/oauth2/token")
            }
            None => format!("http://127.0.0.1:{}/oauth2/token", closed_port()),
        };
        let err = signin::token_request(&http(), &url, Default::default(), body.clone()).await.unwrap_err();
        let permanent = classify(&err) == RefreshClass::Permanent;
        assert_eq!(permanent, r10_permanent(status).unwrap_or(false), "{name}: {err}");
        if c["classify"]["permanent"] == true {
            assert!(permanent, "{name}: permanent in 9router, permanent here");
        }
    }
}
